/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 00:45:23 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Field;
import java.lang.reflect.Member;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ShowClass_ESTest extends ShowClass_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 135 covered goals:
   * Goal 1. ShowClass.main([Ljava/lang/String;)V: root-Branch
   * Goal 2. ShowClass.print_field(Ljava/lang/reflect/Field;)V: root-Branch
   * Goal 3. ShowClass.print_class(Ljava/lang/Class;)V: I4 Branch 1 IFEQ L24 - true
   * Goal 4. ShowClass.print_class(Ljava/lang/Class;)V: I35 Branch 2 IFNULL L28 - false
   * Goal 5. ShowClass.print_class(Ljava/lang/Class;)V: I119 Branch 3 IFNULL L38 - false
   * Goal 6. ShowClass.print_class(Ljava/lang/Class;)V: I122 Branch 4 IFLE L38 - true
   * Goal 7. ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - true
   * Goal 8. ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - false
   * Goal 9. ShowClass.print_class(Ljava/lang/Class;)V: I233 Branch 9 IF_ICMPGE L57 - true
   * Goal 10. ShowClass.print_class(Ljava/lang/Class;)V: I233 Branch 9 IF_ICMPGE L57 - false
   * Goal 11. ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - true
   * Goal 12. ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - false
   * Goal 13. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: I8 Branch 11 IFEQ L71 - true
   * Goal 14. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: I8 Branch 11 IFEQ L71 - false
   * Goal 15. ShowClass.modifiers(I)Ljava/lang/String;: I3 Branch 12 IFNE L80 - true
   * Goal 16. ShowClass.modifiers(I)Ljava/lang/String;: I3 Branch 12 IFNE L80 - false
   * Goal 17. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I8 Branch 13 IFEQ L96 - true
   * Goal 18. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I8 Branch 13 IFEQ L96 - false
   * Goal 19. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I60 Branch 14 IFNULL L107 - true
   * Goal 20. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I60 Branch 14 IFNULL L107 - false
   * Goal 21. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I96 Branch 15 IF_ICMPGE L110 - true
   * Goal 22. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I96 Branch 15 IF_ICMPGE L110 - false
   * Goal 23. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I100 Branch 16 IFLE L111 - true
   * Goal 24. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I100 Branch 16 IFLE L111 - false
   * Goal 25. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I125 Branch 17 IFLE L115 - true
   * Goal 26. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I125 Branch 17 IFLE L115 - false
   * Goal 27. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I137 Branch 18 IF_ICMPGE L116 - true
   * Goal 28. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I137 Branch 18 IF_ICMPGE L116 - false
   * Goal 29. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I141 Branch 19 IFLE L117 - true
   * Goal 30. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I141 Branch 19 IFLE L117 - false
   * Goal 31. Branch ShowClass.main([Ljava/lang/String;)V: root-Branch in context: ShowClass:main([Ljava/lang/String;)V
   * Goal 32. ShowClass.main([Ljava/lang/String;)V: Line 15
   * Goal 33. ShowClass.main([Ljava/lang/String;)V: Line 16
   * Goal 34. ShowClass.main([Ljava/lang/String;)V: Line 17
   * Goal 35. ShowClass.modifiers(I)Ljava/lang/String;: Line 80
   * Goal 36. ShowClass.modifiers(I)Ljava/lang/String;: Line 81
   * Goal 37. ShowClass.print_class(Ljava/lang/Class;)V: Line 24
   * Goal 38. ShowClass.print_class(Ljava/lang/Class;)V: Line 28
   * Goal 39. ShowClass.print_class(Ljava/lang/Class;)V: Line 29
   * Goal 40. ShowClass.print_class(Ljava/lang/Class;)V: Line 30
   * Goal 41. ShowClass.print_class(Ljava/lang/Class;)V: Line 31
   * Goal 42. ShowClass.print_class(Ljava/lang/Class;)V: Line 37
   * Goal 43. ShowClass.print_class(Ljava/lang/Class;)V: Line 38
   * Goal 44. ShowClass.print_class(Ljava/lang/Class;)V: Line 47
   * Goal 45. ShowClass.print_class(Ljava/lang/Class;)V: Line 50
   * Goal 46. ShowClass.print_class(Ljava/lang/Class;)V: Line 51
   * Goal 47. ShowClass.print_class(Ljava/lang/Class;)V: Line 52
   * Goal 48. ShowClass.print_class(Ljava/lang/Class;)V: Line 53
   * Goal 49. ShowClass.print_class(Ljava/lang/Class;)V: Line 55
   * Goal 50. ShowClass.print_class(Ljava/lang/Class;)V: Line 56
   * Goal 51. ShowClass.print_class(Ljava/lang/Class;)V: Line 57
   * Goal 52. ShowClass.print_class(Ljava/lang/Class;)V: Line 58
   * Goal 53. ShowClass.print_class(Ljava/lang/Class;)V: Line 60
   * Goal 54. ShowClass.print_class(Ljava/lang/Class;)V: Line 61
   * Goal 55. ShowClass.print_class(Ljava/lang/Class;)V: Line 62
   * Goal 56. ShowClass.print_class(Ljava/lang/Class;)V: Line 63
   * Goal 57. ShowClass.print_class(Ljava/lang/Class;)V: Line 65
   * Goal 58. ShowClass.print_class(Ljava/lang/Class;)V: Line 66
   * Goal 59. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 86
   * Goal 60. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 87
   * Goal 61. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 88
   * Goal 62. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 89
   * Goal 63. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 95
   * Goal 64. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 96
   * Goal 65. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 97
   * Goal 66. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 98
   * Goal 67. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 99
   * Goal 68. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 100
   * Goal 69. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 101
   * Goal 70. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 102
   * Goal 71. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 103
   * Goal 72. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 104
   * Goal 73. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 107
   * Goal 74. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 108
   * Goal 75. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 109
   * Goal 76. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 110
   * Goal 77. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 111
   * Goal 78. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 112
   * Goal 79. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 114
   * Goal 80. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 115
   * Goal 81. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 116
   * Goal 82. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 117
   * Goal 83. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 118
   * Goal 84. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 120
   * Goal 85. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 121
   * Goal 86. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 70
   * Goal 87. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 71
   * Goal 88. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 72
   * Goal 89. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 73
   * Goal 90. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 75
   * Goal 91. [METHOD] ShowClass.main([Ljava/lang/String;)V
   * Goal 92. [METHODNOEX] ShowClass.main([Ljava/lang/String;)V
   * Goal 93. Weak Mutation 0: ShowClass.main([Ljava/lang/String;)V:15 - ReplaceConstant - 0 -> 1
   * Goal 94. Weak Mutation 1: ShowClass.print_class(Ljava/lang/Class;)V:24 - ReplaceComparisonOperator == -> !=
   * Goal 95. Weak Mutation 4: ShowClass.print_class(Ljava/lang/Class;)V:28 - ReplaceComparisonOperator = null -> != null
   * Goal 96. Weak Mutation 5: ShowClass.print_class(Ljava/lang/Class;)V:29 - ReplaceComparisonOperator == -> !=
   * Goal 97. Weak Mutation 6: ShowClass.print_class(Ljava/lang/Class;)V:29 - ReplaceConstant -  class  -> 
   * Goal 98. Weak Mutation 7: ShowClass.print_class(Ljava/lang/Class;)V:30 - ReplaceConstant -  extends  -> 
   * Goal 99. Weak Mutation 10: ShowClass.print_class(Ljava/lang/Class;)V:37 - ReplaceComparisonOperator == -> !=
   * Goal 100. Weak Mutation 11: ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;:71 - ReplaceComparisonOperator == -> !=
   * Goal 101. Weak Mutation 12: ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;:72 - ReplaceConstant - [] -> 
   * Goal 102. Weak Mutation 13: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp Negation of m
   * Goal 103. Weak Mutation 14: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC 1 m
   * Goal 104. Weak Mutation 15: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC -1 m
   * Goal 105. Weak Mutation 16: ShowClass.modifiers(I)Ljava/lang/String;:80 - ReplaceComparisonOperator != -> -1
   * Goal 106. Weak Mutation 17: ShowClass.modifiers(I)Ljava/lang/String;:80 - ReplaceComparisonOperator != -> <
   * Goal 107. Weak Mutation 19: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp Negation of m
   * Goal 108. Weak Mutation 20: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp IINC 1 m
   * Goal 109. Weak Mutation 21: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp IINC -1 m
   * Goal 110. Weak Mutation 22: ShowClass.modifiers(I)Ljava/lang/String;:81 - ReplaceConstant -   -> 
   * Goal 111. Weak Mutation 23: ShowClass.print_field(Ljava/lang/reflect/Field;)V:86 - ReplaceConstant -    -> 
   * Goal 112. Weak Mutation 24: ShowClass.print_field(Ljava/lang/reflect/Field;)V:88 - ReplaceConstant -   -> 
   * Goal 113. Weak Mutation 25: ShowClass.print_field(Ljava/lang/reflect/Field;)V:88 - ReplaceConstant - ; -> 
   * Goal 114. Weak Mutation 26: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:96 - ReplaceComparisonOperator == -> !=
   * Goal 115. Weak Mutation 27: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:107 - ReplaceConstant -    -> 
   * Goal 116. Weak Mutation 28: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:107 - ReplaceComparisonOperator = null -> != null
   * Goal 117. Weak Mutation 29: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:108 - ReplaceConstant -   -> 
   * Goal 118. Weak Mutation 30: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:109 - ReplaceConstant - ( -> 
   * Goal 119. Weak Mutation 31: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceConstant - 0 -> 1
   * Goal 120. Weak Mutation 32: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - InsertUnaryOp Negation of i
   * Goal 121. Weak Mutation 33: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - InsertUnaryOp IINC 1 i
   * Goal 122. Weak Mutation 34: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - InsertUnaryOp IINC -1 i
   * Goal 123. Weak Mutation 35: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceVariable parameters -> exceptions
   * Goal 124. Weak Mutation 36: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceComparisonOperator >= -> -1
   * Goal 125. Weak Mutation 37: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceComparisonOperator >= -> >
   * Goal 126. Weak Mutation 39: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - InsertUnaryOp Negation of i
   * Goal 127. Weak Mutation 40: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - InsertUnaryOp IINC 1 i
   * Goal 128. Weak Mutation 41: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - InsertUnaryOp IINC -1 i
   * Goal 129. Weak Mutation 42: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - ReplaceComparisonOperator <= -> -1
   * Goal 130. Weak Mutation 44: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - ReplaceComparisonOperator <= -> <
   * Goal 131. Weak Mutation 45: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - ReplaceConstant - ,  -> 
   * Goal 132. Weak Mutation 46: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - ReplaceVariable parameters -> exceptions
   * Goal 133. Weak Mutation 47: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - InsertUnaryOp Negation of i
   * Goal 134. Weak Mutation 48: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - InsertUnaryOp IINC 1 i
   * Goal 135. Weak Mutation 49: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[3];
      stringArray0[0] = "java.lang.reflect.Method";
      ShowClass.main(stringArray0);
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * Goal 1. typename(Ljava/lang/Class;)Ljava/lang/String;_java.lang.NullPointerException_IMPLICIT
   * Goal 2. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 70
   * Goal 3. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 71
   * Goal 4. [METHOD] ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        ShowClass.typename((Class) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * Goal 1. print_class(Ljava/lang/Class;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. ShowClass.print_class(Ljava/lang/Class;)V: Line 24
   * Goal 3. [METHOD] ShowClass.print_class(Ljava/lang/Class;)V
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        ShowClass.print_class((Class) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("ShowClass", e);
      }
  }

  //Test case number: 3
  /*
   * 6 covered goals:
   * Goal 1. ShowClass.main([Ljava/lang/String;)V: root-Branch
   * Goal 2. Branch ShowClass.main([Ljava/lang/String;)V: root-Branch in context: ShowClass:main([Ljava/lang/String;)V
   * Goal 3. main([Ljava/lang/String;)V_java.lang.ClassNotFoundException_DECLARED
   * Goal 4. ShowClass.main([Ljava/lang/String;)V: Line 15
   * Goal 5. [METHOD] ShowClass.main([Ljava/lang/String;)V
   * Goal 6. Weak Mutation 0: ShowClass.main([Ljava/lang/String;)V:15 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "protected private transient volatile native interface ";
      try { 
        ShowClass.main(stringArray0);
        fail("Expecting exception: ClassNotFoundException");
      
      } catch(ClassNotFoundException e) {
      }
  }

  //Test case number: 4
  /*
   * 6 covered goals:
   * Goal 1. ShowClass.main([Ljava/lang/String;)V: root-Branch
   * Goal 2. Branch ShowClass.main([Ljava/lang/String;)V: root-Branch in context: ShowClass:main([Ljava/lang/String;)V
   * Goal 3. main([Ljava/lang/String;)V_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 4. ShowClass.main([Ljava/lang/String;)V: Line 15
   * Goal 5. [METHOD] ShowClass.main([Ljava/lang/String;)V
   * Goal 6. Weak Mutation 0: ShowClass.main([Ljava/lang/String;)V:15 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        ShowClass.main(stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         assertThrownBy("ShowClass", e);
      }
  }

  //Test case number: 5
  /*
   * 9 covered goals:
   * Goal 1. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I8 Branch 13 IFEQ L96 - true
   * Goal 2. Branch ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I8 Branch 13 IFEQ L96 - true in context: ShowClass:print_method_or_constructor(Ljava/lang/reflect/Member;)V
   * Goal 3. print_method_or_constructor(Ljava/lang/reflect/Member;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 4. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 95
   * Goal 5. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 96
   * Goal 6. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 102
   * Goal 7. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 103
   * Goal 8. [METHOD] ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V
   * Goal 9. Weak Mutation 26: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:96 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        ShowClass.print_method_or_constructor((Member) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("ShowClass", e);
      }
  }

  //Test case number: 6
  /*
   * 15 covered goals:
   * Goal 1. ShowClass.modifiers(I)Ljava/lang/String;: I3 Branch 12 IFNE L80 - true
   * Goal 2. Branch ShowClass.modifiers(I)Ljava/lang/String;: I3 Branch 12 IFNE L80 - true in context: ShowClass:modifiers(I)Ljava/lang/String;
   * Goal 3. [Output]: ShowClass.modifiers(I)Ljava/lang/String;:NonEmptyString
   * Goal 4. ShowClass.modifiers(I)Ljava/lang/String;: Line 80
   * Goal 5. ShowClass.modifiers(I)Ljava/lang/String;: Line 81
   * Goal 6. [METHOD] ShowClass.modifiers(I)Ljava/lang/String;
   * Goal 7. [METHODNOEX] ShowClass.modifiers(I)Ljava/lang/String;
   * Goal 8. Weak Mutation 13: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp Negation of m
   * Goal 9. Weak Mutation 14: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC 1 m
   * Goal 10. Weak Mutation 15: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC -1 m
   * Goal 11. Weak Mutation 18: ShowClass.modifiers(I)Ljava/lang/String;:80 - ReplaceComparisonOperator != -> >
   * Goal 12. Weak Mutation 19: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp Negation of m
   * Goal 13. Weak Mutation 20: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp IINC 1 m
   * Goal 14. Weak Mutation 21: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp IINC -1 m
   * Goal 15. Weak Mutation 22: ShowClass.modifiers(I)Ljava/lang/String;:81 - ReplaceConstant -   -> 
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = ShowClass.modifiers((-586));
      assertEquals("protected private abstract final transient synchronized native strictfp ", string0);
  }

  //Test case number: 7
  /*
   * 10 covered goals:
   * Goal 1. ShowClass.modifiers(I)Ljava/lang/String;: I3 Branch 12 IFNE L80 - false
   * Goal 2. Branch ShowClass.modifiers(I)Ljava/lang/String;: I3 Branch 12 IFNE L80 - false in context: ShowClass:modifiers(I)Ljava/lang/String;
   * Goal 3. [Output]: ShowClass.modifiers(I)Ljava/lang/String;:EmptyString
   * Goal 4. ShowClass.modifiers(I)Ljava/lang/String;: Line 80
   * Goal 5. [METHOD] ShowClass.modifiers(I)Ljava/lang/String;
   * Goal 6. [METHODNOEX] ShowClass.modifiers(I)Ljava/lang/String;
   * Goal 7. Weak Mutation 13: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp Negation of m
   * Goal 8. Weak Mutation 14: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC 1 m
   * Goal 9. Weak Mutation 15: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC -1 m
   * Goal 10. Weak Mutation 16: ShowClass.modifiers(I)Ljava/lang/String;:80 - ReplaceComparisonOperator != -> -1
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = ShowClass.modifiers(0);
      assertEquals("", string0);
  }

  //Test case number: 8
  /*
   * 9 covered goals:
   * Goal 1. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: I8 Branch 11 IFEQ L71 - true
   * Goal 2. Branch ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: I8 Branch 11 IFEQ L71 - true in context: ShowClass:typename(Ljava/lang/Class;)Ljava/lang/String;
   * Goal 3. [Output]: ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;:NonEmptyString
   * Goal 4. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 70
   * Goal 5. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 71
   * Goal 6. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 75
   * Goal 7. [METHOD] ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;
   * Goal 8. [METHODNOEX] ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;
   * Goal 9. Weak Mutation 11: ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;:71 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      String string0 = ShowClass.typename(class0);
      assertEquals("java.lang.Integer", string0);
  }

  //Test case number: 9
  /*
   * 7 covered goals:
   * Goal 1. ShowClass.print_field(Ljava/lang/reflect/Field;)V: root-Branch
   * Goal 2. Branch ShowClass.print_field(Ljava/lang/reflect/Field;)V: root-Branch in context: ShowClass:print_field(Ljava/lang/reflect/Field;)V
   * Goal 3. print_field(Ljava/lang/reflect/Field;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 4. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 86
   * Goal 5. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 87
   * Goal 6. [METHOD] ShowClass.print_field(Ljava/lang/reflect/Field;)V
   * Goal 7. Weak Mutation 23: ShowClass.print_field(Ljava/lang/reflect/Field;)V:86 - ReplaceConstant -    -> 
   */

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        ShowClass.print_field((Field) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("ShowClass", e);
      }
  }

  //Test case number: 10
  /*
   * 153 covered goals:
   * Goal 1. ShowClass.print_field(Ljava/lang/reflect/Field;)V: root-Branch
   * Goal 2. ShowClass.print_class(Ljava/lang/Class;)V: I4 Branch 1 IFEQ L24 - true
   * Goal 3. ShowClass.print_class(Ljava/lang/Class;)V: I35 Branch 2 IFNULL L28 - false
   * Goal 4. ShowClass.print_class(Ljava/lang/Class;)V: I119 Branch 3 IFNULL L38 - false
   * Goal 5. ShowClass.print_class(Ljava/lang/Class;)V: I122 Branch 4 IFLE L38 - false
   * Goal 6. ShowClass.print_class(Ljava/lang/Class;)V: I127 Branch 5 IFEQ L39 - true
   * Goal 7. ShowClass.print_class(Ljava/lang/Class;)V: I145 Branch 6 IF_ICMPGE L41 - true
   * Goal 8. ShowClass.print_class(Ljava/lang/Class;)V: I145 Branch 6 IF_ICMPGE L41 - false
   * Goal 9. ShowClass.print_class(Ljava/lang/Class;)V: I149 Branch 7 IFLE L42 - true
   * Goal 10. ShowClass.print_class(Ljava/lang/Class;)V: I149 Branch 7 IFLE L42 - false
   * Goal 11. ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - true
   * Goal 12. ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - false
   * Goal 13. ShowClass.print_class(Ljava/lang/Class;)V: I233 Branch 9 IF_ICMPGE L57 - true
   * Goal 14. ShowClass.print_class(Ljava/lang/Class;)V: I233 Branch 9 IF_ICMPGE L57 - false
   * Goal 15. ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - true
   * Goal 16. ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - false
   * Goal 17. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: I8 Branch 11 IFEQ L71 - true
   * Goal 18. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: I8 Branch 11 IFEQ L71 - false
   * Goal 19. ShowClass.modifiers(I)Ljava/lang/String;: I3 Branch 12 IFNE L80 - true
   * Goal 20. ShowClass.modifiers(I)Ljava/lang/String;: I3 Branch 12 IFNE L80 - false
   * Goal 21. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I8 Branch 13 IFEQ L96 - true
   * Goal 22. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I8 Branch 13 IFEQ L96 - false
   * Goal 23. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I60 Branch 14 IFNULL L107 - true
   * Goal 24. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I60 Branch 14 IFNULL L107 - false
   * Goal 25. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I96 Branch 15 IF_ICMPGE L110 - true
   * Goal 26. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I96 Branch 15 IF_ICMPGE L110 - false
   * Goal 27. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I100 Branch 16 IFLE L111 - true
   * Goal 28. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I100 Branch 16 IFLE L111 - false
   * Goal 29. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I125 Branch 17 IFLE L115 - true
   * Goal 30. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I125 Branch 17 IFLE L115 - false
   * Goal 31. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I137 Branch 18 IF_ICMPGE L116 - true
   * Goal 32. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I137 Branch 18 IF_ICMPGE L116 - false
   * Goal 33. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I141 Branch 19 IFLE L117 - true
   * Goal 34. Branch ShowClass.print_class(Ljava/lang/Class;)V: I4 Branch 1 IFEQ L24 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 35. Branch ShowClass.print_class(Ljava/lang/Class;)V: I35 Branch 2 IFNULL L28 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 36. Branch ShowClass.print_class(Ljava/lang/Class;)V: I119 Branch 3 IFNULL L38 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 37. Branch ShowClass.print_class(Ljava/lang/Class;)V: I122 Branch 4 IFLE L38 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 38. Branch ShowClass.print_class(Ljava/lang/Class;)V: I127 Branch 5 IFEQ L39 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 39. Branch ShowClass.print_class(Ljava/lang/Class;)V: I145 Branch 6 IF_ICMPGE L41 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 40. Branch ShowClass.print_class(Ljava/lang/Class;)V: I145 Branch 6 IF_ICMPGE L41 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 41. Branch ShowClass.print_class(Ljava/lang/Class;)V: I149 Branch 7 IFLE L42 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 42. Branch ShowClass.print_class(Ljava/lang/Class;)V: I149 Branch 7 IFLE L42 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 43. Branch ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 44. Branch ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 45. Branch ShowClass.print_class(Ljava/lang/Class;)V: I233 Branch 9 IF_ICMPGE L57 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 46. Branch ShowClass.print_class(Ljava/lang/Class;)V: I233 Branch 9 IF_ICMPGE L57 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 47. Branch ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 48. Branch ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 49. ShowClass.modifiers(I)Ljava/lang/String;: Line 80
   * Goal 50. ShowClass.modifiers(I)Ljava/lang/String;: Line 81
   * Goal 51. ShowClass.print_class(Ljava/lang/Class;)V: Line 24
   * Goal 52. ShowClass.print_class(Ljava/lang/Class;)V: Line 28
   * Goal 53. ShowClass.print_class(Ljava/lang/Class;)V: Line 29
   * Goal 54. ShowClass.print_class(Ljava/lang/Class;)V: Line 30
   * Goal 55. ShowClass.print_class(Ljava/lang/Class;)V: Line 31
   * Goal 56. ShowClass.print_class(Ljava/lang/Class;)V: Line 37
   * Goal 57. ShowClass.print_class(Ljava/lang/Class;)V: Line 38
   * Goal 58. ShowClass.print_class(Ljava/lang/Class;)V: Line 39
   * Goal 59. ShowClass.print_class(Ljava/lang/Class;)V: Line 40
   * Goal 60. ShowClass.print_class(Ljava/lang/Class;)V: Line 41
   * Goal 61. ShowClass.print_class(Ljava/lang/Class;)V: Line 42
   * Goal 62. ShowClass.print_class(Ljava/lang/Class;)V: Line 43
   * Goal 63. ShowClass.print_class(Ljava/lang/Class;)V: Line 47
   * Goal 64. ShowClass.print_class(Ljava/lang/Class;)V: Line 50
   * Goal 65. ShowClass.print_class(Ljava/lang/Class;)V: Line 51
   * Goal 66. ShowClass.print_class(Ljava/lang/Class;)V: Line 52
   * Goal 67. ShowClass.print_class(Ljava/lang/Class;)V: Line 53
   * Goal 68. ShowClass.print_class(Ljava/lang/Class;)V: Line 55
   * Goal 69. ShowClass.print_class(Ljava/lang/Class;)V: Line 56
   * Goal 70. ShowClass.print_class(Ljava/lang/Class;)V: Line 57
   * Goal 71. ShowClass.print_class(Ljava/lang/Class;)V: Line 58
   * Goal 72. ShowClass.print_class(Ljava/lang/Class;)V: Line 60
   * Goal 73. ShowClass.print_class(Ljava/lang/Class;)V: Line 61
   * Goal 74. ShowClass.print_class(Ljava/lang/Class;)V: Line 62
   * Goal 75. ShowClass.print_class(Ljava/lang/Class;)V: Line 63
   * Goal 76. ShowClass.print_class(Ljava/lang/Class;)V: Line 65
   * Goal 77. ShowClass.print_class(Ljava/lang/Class;)V: Line 66
   * Goal 78. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 86
   * Goal 79. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 87
   * Goal 80. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 88
   * Goal 81. ShowClass.print_field(Ljava/lang/reflect/Field;)V: Line 89
   * Goal 82. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 95
   * Goal 83. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 96
   * Goal 84. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 97
   * Goal 85. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 98
   * Goal 86. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 99
   * Goal 87. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 100
   * Goal 88. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 101
   * Goal 89. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 102
   * Goal 90. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 103
   * Goal 91. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 104
   * Goal 92. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 107
   * Goal 93. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 108
   * Goal 94. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 109
   * Goal 95. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 110
   * Goal 96. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 111
   * Goal 97. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 112
   * Goal 98. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 114
   * Goal 99. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 115
   * Goal 100. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 116
   * Goal 101. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 117
   * Goal 102. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 118
   * Goal 103. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 120
   * Goal 104. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 121
   * Goal 105. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 70
   * Goal 106. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 71
   * Goal 107. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 72
   * Goal 108. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 73
   * Goal 109. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 75
   * Goal 110. [METHOD] ShowClass.print_class(Ljava/lang/Class;)V
   * Goal 111. [METHODNOEX] ShowClass.print_class(Ljava/lang/Class;)V
   * Goal 112. Weak Mutation 1: ShowClass.print_class(Ljava/lang/Class;)V:24 - ReplaceComparisonOperator == -> !=
   * Goal 113. Weak Mutation 4: ShowClass.print_class(Ljava/lang/Class;)V:28 - ReplaceComparisonOperator = null -> != null
   * Goal 114. Weak Mutation 5: ShowClass.print_class(Ljava/lang/Class;)V:29 - ReplaceComparisonOperator == -> !=
   * Goal 115. Weak Mutation 6: ShowClass.print_class(Ljava/lang/Class;)V:29 - ReplaceConstant -  class  -> 
   * Goal 116. Weak Mutation 7: ShowClass.print_class(Ljava/lang/Class;)V:30 - ReplaceConstant -  extends  -> 
   * Goal 117. Weak Mutation 10: ShowClass.print_class(Ljava/lang/Class;)V:37 - ReplaceComparisonOperator == -> !=
   * Goal 118. Weak Mutation 11: ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;:71 - ReplaceComparisonOperator == -> !=
   * Goal 119. Weak Mutation 12: ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;:72 - ReplaceConstant - [] -> 
   * Goal 120. Weak Mutation 13: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp Negation of m
   * Goal 121. Weak Mutation 14: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC 1 m
   * Goal 122. Weak Mutation 15: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC -1 m
   * Goal 123. Weak Mutation 16: ShowClass.modifiers(I)Ljava/lang/String;:80 - ReplaceComparisonOperator != -> -1
   * Goal 124. Weak Mutation 17: ShowClass.modifiers(I)Ljava/lang/String;:80 - ReplaceComparisonOperator != -> <
   * Goal 125. Weak Mutation 19: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp Negation of m
   * Goal 126. Weak Mutation 20: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp IINC 1 m
   * Goal 127. Weak Mutation 21: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp IINC -1 m
   * Goal 128. Weak Mutation 22: ShowClass.modifiers(I)Ljava/lang/String;:81 - ReplaceConstant -   -> 
   * Goal 129. Weak Mutation 23: ShowClass.print_field(Ljava/lang/reflect/Field;)V:86 - ReplaceConstant -    -> 
   * Goal 130. Weak Mutation 24: ShowClass.print_field(Ljava/lang/reflect/Field;)V:88 - ReplaceConstant -   -> 
   * Goal 131. Weak Mutation 25: ShowClass.print_field(Ljava/lang/reflect/Field;)V:88 - ReplaceConstant - ; -> 
   * Goal 132. Weak Mutation 26: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:96 - ReplaceComparisonOperator == -> !=
   * Goal 133. Weak Mutation 27: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:107 - ReplaceConstant -    -> 
   * Goal 134. Weak Mutation 28: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:107 - ReplaceComparisonOperator = null -> != null
   * Goal 135. Weak Mutation 29: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:108 - ReplaceConstant -   -> 
   * Goal 136. Weak Mutation 30: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:109 - ReplaceConstant - ( -> 
   * Goal 137. Weak Mutation 31: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceConstant - 0 -> 1
   * Goal 138. Weak Mutation 32: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - InsertUnaryOp Negation of i
   * Goal 139. Weak Mutation 33: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - InsertUnaryOp IINC 1 i
   * Goal 140. Weak Mutation 34: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - InsertUnaryOp IINC -1 i
   * Goal 141. Weak Mutation 35: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceVariable parameters -> exceptions
   * Goal 142. Weak Mutation 36: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceComparisonOperator >= -> -1
   * Goal 143. Weak Mutation 37: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceComparisonOperator >= -> >
   * Goal 144. Weak Mutation 39: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - InsertUnaryOp Negation of i
   * Goal 145. Weak Mutation 40: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - InsertUnaryOp IINC 1 i
   * Goal 146. Weak Mutation 41: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - InsertUnaryOp IINC -1 i
   * Goal 147. Weak Mutation 42: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - ReplaceComparisonOperator <= -> -1
   * Goal 148. Weak Mutation 44: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - ReplaceComparisonOperator <= -> <
   * Goal 149. Weak Mutation 45: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - ReplaceConstant - ,  -> 
   * Goal 150. Weak Mutation 46: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - ReplaceVariable parameters -> exceptions
   * Goal 151. Weak Mutation 47: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - InsertUnaryOp Negation of i
   * Goal 152. Weak Mutation 48: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - InsertUnaryOp IINC 1 i
   * Goal 153. Weak Mutation 49: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Class<String> class0 = String.class;
      ShowClass.print_class(class0);
  }

  //Test case number: 11
  /*
   * 119 covered goals:
   * Goal 1. ShowClass.print_class(Ljava/lang/Class;)V: I4 Branch 1 IFEQ L24 - true
   * Goal 2. ShowClass.print_class(Ljava/lang/Class;)V: I35 Branch 2 IFNULL L28 - true
   * Goal 3. ShowClass.print_class(Ljava/lang/Class;)V: I119 Branch 3 IFNULL L38 - false
   * Goal 4. ShowClass.print_class(Ljava/lang/Class;)V: I122 Branch 4 IFLE L38 - true
   * Goal 5. ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - true
   * Goal 6. ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - false
   * Goal 7. ShowClass.print_class(Ljava/lang/Class;)V: I233 Branch 9 IF_ICMPGE L57 - true
   * Goal 8. ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - true
   * Goal 9. ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - false
   * Goal 10. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: I8 Branch 11 IFEQ L71 - true
   * Goal 11. ShowClass.modifiers(I)Ljava/lang/String;: I3 Branch 12 IFNE L80 - true
   * Goal 12. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I8 Branch 13 IFEQ L96 - true
   * Goal 13. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I8 Branch 13 IFEQ L96 - false
   * Goal 14. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I60 Branch 14 IFNULL L107 - true
   * Goal 15. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I60 Branch 14 IFNULL L107 - false
   * Goal 16. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I96 Branch 15 IF_ICMPGE L110 - true
   * Goal 17. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I96 Branch 15 IF_ICMPGE L110 - false
   * Goal 18. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I100 Branch 16 IFLE L111 - true
   * Goal 19. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I100 Branch 16 IFLE L111 - false
   * Goal 20. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I125 Branch 17 IFLE L115 - true
   * Goal 21. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I125 Branch 17 IFLE L115 - false
   * Goal 22. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I137 Branch 18 IF_ICMPGE L116 - true
   * Goal 23. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I137 Branch 18 IF_ICMPGE L116 - false
   * Goal 24. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: I141 Branch 19 IFLE L117 - true
   * Goal 25. Branch ShowClass.print_class(Ljava/lang/Class;)V: I4 Branch 1 IFEQ L24 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 26. Branch ShowClass.print_class(Ljava/lang/Class;)V: I35 Branch 2 IFNULL L28 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 27. Branch ShowClass.print_class(Ljava/lang/Class;)V: I119 Branch 3 IFNULL L38 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 28. Branch ShowClass.print_class(Ljava/lang/Class;)V: I122 Branch 4 IFLE L38 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 29. Branch ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 30. Branch ShowClass.print_class(Ljava/lang/Class;)V: I196 Branch 8 IF_ICMPGE L52 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 31. Branch ShowClass.print_class(Ljava/lang/Class;)V: I233 Branch 9 IF_ICMPGE L57 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 32. Branch ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - false in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 33. Branch ShowClass.print_class(Ljava/lang/Class;)V: I270 Branch 10 IF_ICMPGE L62 - true in context: ShowClass:print_class(Ljava/lang/Class;)V
   * Goal 34. ShowClass.modifiers(I)Ljava/lang/String;: Line 80
   * Goal 35. ShowClass.modifiers(I)Ljava/lang/String;: Line 81
   * Goal 36. ShowClass.print_class(Ljava/lang/Class;)V: Line 24
   * Goal 37. ShowClass.print_class(Ljava/lang/Class;)V: Line 28
   * Goal 38. ShowClass.print_class(Ljava/lang/Class;)V: Line 33
   * Goal 39. ShowClass.print_class(Ljava/lang/Class;)V: Line 34
   * Goal 40. ShowClass.print_class(Ljava/lang/Class;)V: Line 37
   * Goal 41. ShowClass.print_class(Ljava/lang/Class;)V: Line 38
   * Goal 42. ShowClass.print_class(Ljava/lang/Class;)V: Line 47
   * Goal 43. ShowClass.print_class(Ljava/lang/Class;)V: Line 50
   * Goal 44. ShowClass.print_class(Ljava/lang/Class;)V: Line 51
   * Goal 45. ShowClass.print_class(Ljava/lang/Class;)V: Line 52
   * Goal 46. ShowClass.print_class(Ljava/lang/Class;)V: Line 53
   * Goal 47. ShowClass.print_class(Ljava/lang/Class;)V: Line 55
   * Goal 48. ShowClass.print_class(Ljava/lang/Class;)V: Line 56
   * Goal 49. ShowClass.print_class(Ljava/lang/Class;)V: Line 57
   * Goal 50. ShowClass.print_class(Ljava/lang/Class;)V: Line 60
   * Goal 51. ShowClass.print_class(Ljava/lang/Class;)V: Line 61
   * Goal 52. ShowClass.print_class(Ljava/lang/Class;)V: Line 62
   * Goal 53. ShowClass.print_class(Ljava/lang/Class;)V: Line 63
   * Goal 54. ShowClass.print_class(Ljava/lang/Class;)V: Line 65
   * Goal 55. ShowClass.print_class(Ljava/lang/Class;)V: Line 66
   * Goal 56. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 95
   * Goal 57. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 96
   * Goal 58. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 97
   * Goal 59. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 98
   * Goal 60. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 99
   * Goal 61. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 100
   * Goal 62. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 101
   * Goal 63. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 102
   * Goal 64. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 103
   * Goal 65. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 104
   * Goal 66. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 107
   * Goal 67. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 108
   * Goal 68. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 109
   * Goal 69. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 110
   * Goal 70. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 111
   * Goal 71. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 112
   * Goal 72. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 114
   * Goal 73. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 115
   * Goal 74. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 116
   * Goal 75. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 117
   * Goal 76. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 118
   * Goal 77. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 120
   * Goal 78. ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V: Line 121
   * Goal 79. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 70
   * Goal 80. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 71
   * Goal 81. ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;: Line 75
   * Goal 82. [METHOD] ShowClass.print_class(Ljava/lang/Class;)V
   * Goal 83. [METHODNOEX] ShowClass.print_class(Ljava/lang/Class;)V
   * Goal 84. Weak Mutation 1: ShowClass.print_class(Ljava/lang/Class;)V:24 - ReplaceComparisonOperator == -> !=
   * Goal 85. Weak Mutation 4: ShowClass.print_class(Ljava/lang/Class;)V:28 - ReplaceComparisonOperator = null -> != null
   * Goal 86. Weak Mutation 8: ShowClass.print_class(Ljava/lang/Class;)V:33 - ReplaceComparisonOperator == -> !=
   * Goal 87. Weak Mutation 9: ShowClass.print_class(Ljava/lang/Class;)V:33 - ReplaceConstant -  class  -> 
   * Goal 88. Weak Mutation 10: ShowClass.print_class(Ljava/lang/Class;)V:37 - ReplaceComparisonOperator == -> !=
   * Goal 89. Weak Mutation 11: ShowClass.typename(Ljava/lang/Class;)Ljava/lang/String;:71 - ReplaceComparisonOperator == -> !=
   * Goal 90. Weak Mutation 13: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp Negation of m
   * Goal 91. Weak Mutation 14: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC 1 m
   * Goal 92. Weak Mutation 15: ShowClass.modifiers(I)Ljava/lang/String;:80 - InsertUnaryOp IINC -1 m
   * Goal 93. Weak Mutation 17: ShowClass.modifiers(I)Ljava/lang/String;:80 - ReplaceComparisonOperator != -> <
   * Goal 94. Weak Mutation 19: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp Negation of m
   * Goal 95. Weak Mutation 20: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp IINC 1 m
   * Goal 96. Weak Mutation 21: ShowClass.modifiers(I)Ljava/lang/String;:81 - InsertUnaryOp IINC -1 m
   * Goal 97. Weak Mutation 22: ShowClass.modifiers(I)Ljava/lang/String;:81 - ReplaceConstant -   -> 
   * Goal 98. Weak Mutation 26: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:96 - ReplaceComparisonOperator == -> !=
   * Goal 99. Weak Mutation 27: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:107 - ReplaceConstant -    -> 
   * Goal 100. Weak Mutation 28: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:107 - ReplaceComparisonOperator = null -> != null
   * Goal 101. Weak Mutation 29: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:108 - ReplaceConstant -   -> 
   * Goal 102. Weak Mutation 30: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:109 - ReplaceConstant - ( -> 
   * Goal 103. Weak Mutation 31: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceConstant - 0 -> 1
   * Goal 104. Weak Mutation 32: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - InsertUnaryOp Negation of i
   * Goal 105. Weak Mutation 33: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - InsertUnaryOp IINC 1 i
   * Goal 106. Weak Mutation 34: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - InsertUnaryOp IINC -1 i
   * Goal 107. Weak Mutation 35: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceVariable parameters -> exceptions
   * Goal 108. Weak Mutation 36: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceComparisonOperator >= -> -1
   * Goal 109. Weak Mutation 37: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:110 - ReplaceComparisonOperator >= -> >
   * Goal 110. Weak Mutation 39: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - InsertUnaryOp Negation of i
   * Goal 111. Weak Mutation 40: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - InsertUnaryOp IINC 1 i
   * Goal 112. Weak Mutation 41: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - InsertUnaryOp IINC -1 i
   * Goal 113. Weak Mutation 42: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - ReplaceComparisonOperator <= -> -1
   * Goal 114. Weak Mutation 44: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - ReplaceComparisonOperator <= -> <
   * Goal 115. Weak Mutation 45: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:111 - ReplaceConstant - ,  -> 
   * Goal 116. Weak Mutation 46: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - ReplaceVariable parameters -> exceptions
   * Goal 117. Weak Mutation 47: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - InsertUnaryOp Negation of i
   * Goal 118. Weak Mutation 48: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - InsertUnaryOp IINC 1 i
   * Goal 119. Weak Mutation 49: ShowClass.print_method_or_constructor(Ljava/lang/reflect/Member;)V:112 - InsertUnaryOp IINC -1 i
   */

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Class<Object> class0 = Object.class;
      ShowClass.print_class(class0);
  }

  //Test case number: 12
  /*
   * 6 covered goals:
   * Goal 1. ShowClass.main([Ljava/lang/String;)V: root-Branch
   * Goal 2. Branch ShowClass.main([Ljava/lang/String;)V: root-Branch in context: ShowClass:main([Ljava/lang/String;)V
   * Goal 3. main([Ljava/lang/String;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 4. ShowClass.main([Ljava/lang/String;)V: Line 15
   * Goal 5. [METHOD] ShowClass.main([Ljava/lang/String;)V
   * Goal 6. Weak Mutation 0: ShowClass.main([Ljava/lang/String;)V:15 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        ShowClass.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.lang.Class", e);
      }
  }

  //Test case number: 13
  /*
   * 4 covered goals:
   * Goal 1. ShowClass.<init>()V: root-Branch
   * Goal 2. Branch ShowClass.<init>()V: root-Branch in context: ShowClass:<init>()V
   * Goal 3. [METHOD] ShowClass.<init>()V
   * Goal 4. [METHODNOEX] ShowClass.<init>()V
   */

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ShowClass showClass0 = new ShowClass();
  }
}
